### ISSUE TITLE
Altyazı

### ISSUE THREAD

**Issue by ghost** [fatihacet/vuejs-videolari#1]
İşitme engelliler için Türkçe, daha geniş bir kitleye ulaşmak için de İngilizce altyazı eklenebilir. Seriyi beğenenlerce küçük bir topluluk kurup böyle bir topa girilebilir, ne dersin?

**Comment by fatihacet** [comment]
Olur derim :) Ama cok uzun bir efor, o yuzden gonulluler cikarsa olabilir.
